"
This class represent a neural layer build on top of TensorFlow. This is a fully connected layer.

This class allow to manage layers and TF session and graph.

This class is on build based of work on libtensorflowpharobindings with respect of Matrix Neural Network of agileartificialintelligence. 

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.

    Instance Variables
	neurons:		<Object>


    Implementation Points
"
Class {
	#name : #TFNeuralLayer,
	#superclass : #Object,
	#category : #libtensorflowNeuralNetwork
}
